#!/usr/bin/env bash
#
# applenix installer — stage 1, for any Apple Silicon Mac.
#
# Run this as root from the nixos-apple-silicon USB installer:
#
#   curl -fsSL https://raw.githubusercontent.com/teoscloud/teonix/main/hosts/applenix/install.sh | bash
#
# It is idempotent: re-run the exact same command after any failure and the
# steps that already succeeded are skipped.
#
# Stage 1 deliberately does NOT use the teonix flake. It generates a plain
# /mnt/etc/nixos/configuration.nix against the ISO's own nixpkgs and the ISO's
# own apple-silicon-support module, so nixos-install copies the Asahi kernel
# out of the installer instead of rebuilding it (which OOMs in the installer,
# and there is no upstream binary cache for it).
#
# Stage 2 (the teonix Hyprland rice) runs from the booted Mac:
#   /etc/applenix/stage2.sh
#
# -E so the ERR trap below also fires for failures inside functions.
set -Eeuo pipefail

readonly VERSION=9
readonly SELF="applenix-install"
readonly CURL_CMD="curl -fsSL https://raw.githubusercontent.com/teoscloud/teonix/main/hosts/applenix/install.sh | bash"

readonly STEPS=(
  detect
  net
  disk
  format
  mount
  firmware
  config
  install
  stage2
  summary
)

# Everything below can be overridden from the environment.
TARGET_USER="${TARGET_USER:-teodor}"
TARGET_HOST="${TARGET_HOST:-applenix}"
TEONIX_REPO="${TEONIX_REPO:-https://github.com/teoscloud/teonix.git}"
TEONIX_DIR="${TEONIX_DIR:-/home/${TARGET_USER}/teonix}"
CHARGE_LIMIT="${CHARGE_LIMIT:-80}"
FACTS="${FACTS:-/tmp/applenix-facts}"

readonly ROOT_LABEL=nixos
# TARGET=/ lets you regenerate stage2.sh on an already-booted applenix:
#   sudo TARGET=/ bash install.sh run stage2
TARGET="${TARGET:-/mnt}"
NIXOS_DIR="${TARGET%/}/etc/nixos"
FW_DIR="${NIXOS_DIR}/firmware"
STAGE2="${TARGET%/}/etc/applenix/stage2.sh"
readonly CONFIG_MARKER="# generated by ${SELF} v"

# ---------------------------------------------------------------- output ----

say() { printf '%s\n' "$*"; }
info() { printf '       %s\n' "$*"; }
ok() { printf '[ ok ] %s\n' "$*"; }
skip() { printf '[skip] %s\n' "$*"; }
runmsg() { printf '[ run] %s\n' "$*"; }
warn() { printf '[warn] %s\n' "$*" >&2; }
die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

CURRENT_STEP=""

on_err() {
  local code=$?
  [[ -n $CURRENT_STEP ]] || exit "$code"
  printf '\n' >&2
  printf 'error: step "%s" failed (exit %d)\n' "$CURRENT_STEP" "$code" >&2
  printf '       fix the cause and re-run the same command; finished steps are skipped:\n' >&2
  printf '         %s\n' "$CURL_CMD" >&2
  exit "$code"
}
trap on_err ERR

need_root() { [[ $(id -u) -eq 0 ]] || die "run as root first: sudo su"; }

# Prompts read the tty directly so `curl … | bash` stays interactive.
confirm() {
  local question=$1 answer
  [[ ${YES:-0} == 1 ]] && return 0
  [[ -r /dev/tty ]] || die "no tty available for confirmation — re-run with YES=1"
  printf '%s [type YES]: ' "$question" >/dev/tty
  read -r answer </dev/tty || die "aborted"
  [[ $answer == YES ]] || die "aborted"
}

# ----------------------------------------------------------------- facts ----

fact_set() {
  local key=$1 value=$2 tmp
  mkdir -p "$(dirname "$FACTS")"
  : >>"$FACTS"
  tmp=$(mktemp)
  grep -v "^${key}=" "$FACTS" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  LC_ALL=C sort -o "$FACTS" "$tmp"
  rm -f "$tmp"
}

fact_get() {
  local key=$1 value
  [[ -f $FACTS ]] || return 1
  value=$(sed -n "s/^${key}=//p" "$FACTS" | tail -n1)
  [[ -n $value ]] || return 1
  printf '%s\n' "$value"
}

fact_or() {
  fact_get "$1" 2>/dev/null || printf '%s\n' "$2"
}

# ------------------------------------------------------------- detection ----

# Device-tree properties are NUL-terminated.
dt_string() {
  [[ -e $1 ]] || return 1
  tr -d '\0' <"$1"
}

dt_list() {
  [[ -e $1 ]] || return 1
  tr '\0' ' ' <"$1"
}

esp_partuuid() {
  dt_string /proc/device-tree/chosen/asahi,efi-system-partition
}

esp_dev() {
  local uuid
  uuid=$(esp_partuuid) || return 1
  [[ -n $uuid ]] || return 1
  printf '/dev/disk/by-partuuid/%s\n' "$uuid"
}

# The ESP the Asahi installer made for us identifies the disk to install on.
# Never assume /dev/nvme0n1: Mac Pro and external-boot setups differ.
detect_disk() {
  local esp resolved parent
  if [[ -n ${DISK:-} ]]; then
    printf '%s\n' "$DISK"
    return 0
  fi
  esp=$(esp_dev) || return 1
  resolved=$(readlink -f "$esp" 2>/dev/null) || return 1
  [[ -b $resolved ]] || return 1
  parent=$(lsblk -npo PKNAME "$resolved" 2>/dev/null | head -n1)
  [[ -n $parent ]] || return 1
  printf '%s\n' "$parent"
}

# A battery means a laptop. Cheaper and more future-proof than a model table.
detect_chassis() {
  local ps
  for ps in /sys/class/power_supply/*; do
    [[ -e $ps/type ]] || continue
    [[ $(cat "$ps/type" 2>/dev/null) == Battery ]] && {
      printf 'laptop\n'
      return 0
    }
  done
  printf 'desktop\n'
}

detect_touchbar() {
  local card driver
  if [[ -n ${TOUCHBAR:-} ]]; then
    printf '%s\n' "$TOUCHBAR"
    return 0
  fi
  for card in /sys/class/drm/card*; do
    [[ -e $card/device/driver ]] || continue
    driver=$(basename "$(readlink -f "$card/device/driver")")
    [[ $driver == appletbdrm ]] && {
      printf 'yes\n'
      return 0
    }
  done
  [[ -e /sys/class/backlight/appletb_backlight ]] && {
    printf 'yes\n'
    return 0
  }
  printf 'no\n'
}

detect_displays() {
  local connector name out=()
  for connector in /sys/class/drm/card*-*; do
    [[ -r $connector/status ]] || continue
    [[ $(cat "$connector/status" 2>/dev/null) == connected ]] || continue
    name=${connector##*/}
    out+=("${name#*-}")
  done
  ((${#out[@]})) || return 1
  local IFS=,
  printf '%s\n' "${out[*]}"
}

detect_wifi() {
  local iface out=()
  for iface in /sys/class/net/*; do
    [[ -d $iface/wireless ]] || continue
    out+=("${iface##*/}")
  done
  ((${#out[@]})) && printf '%s\n' "${out[0]}"
}

detect_ram_mb() { awk '/^MemTotal:/ { printf "%d\n", $2 / 1024 }' /proc/meminfo; }

detect_release() { nixos-version 2>/dev/null | cut -d. -f1,2; }

# Kernel and rust builds are memory-hungry; too many parallel jobs OOM an 8 GB
# Mac, too few waste an M4 Max. Derive from RAM instead of hardcoding.
derive_max_jobs() {
  local gb=$1
  if ((gb <= 8)); then
    printf '1\n'
  elif ((gb <= 16)); then
    printf '2\n'
  else
    printf '4\n'
  fi
}

# The stage 2 kernel build wants far more than an 8 GB Mac has. Swap is cheap
# on disk and is the difference between "slow" and "Killed".
derive_swap_mb() {
  local gb=$1
  [[ -n ${SWAP_SIZE:-} ]] && {
    printf '%s\n' "$SWAP_SIZE"
    return 0
  }
  if ((gb <= 8)); then
    printf '16384\n'
  elif ((gb <= 16)); then
    printf '12288\n'
  else
    printf '8192\n'
  fi
}

# Parallelism inside one derivation. Peak memory scales with this, and rustc on
# the Asahi kernel is heavy, so a small Mac must not use every core.
derive_build_cores() {
  local gb=$1
  [[ -n ${BUILD_CORES:-} ]] && {
    printf '%s\n' "$BUILD_CORES"
    return 0
  }
  if ((gb <= 8)); then
    printf '2\n'
  elif ((gb <= 16)); then
    printf '4\n'
  else
    printf '0\n' # 0 = all cores
  fi
}

# ------------------------------------------------------------ disk tools ----

reread_pt() {
  local disk=$1
  partprobe "$disk" 2>/dev/null || blockdev --rereadpt "$disk" 2>/dev/null || true
  udevadm settle 2>/dev/null || sleep 1
}

list_parts() {
  lsblk -nrpo NAME,TYPE "$1" 2>/dev/null | awk '$2 == "part" { print $1 }'
}

# 0fc63daf-… is the GPT GUID behind sgdisk's 8300 "Linux filesystem" code.
list_linux_parts() {
  lsblk -nrpo NAME,TYPE,PARTTYPE "$1" 2>/dev/null \
    | awk 'tolower($3) == "0fc63daf-8483-4772-8e79-3d69d8477de4" && $2 == "part" { print $1 }'
}

labeled_root() {
  local dev="/dev/disk/by-label/${ROOT_LABEL}"
  [[ -b $dev ]] || return 1
  readlink -f "$dev"
}

find_fwextract() {
  local candidate
  if command -v asahi-fwextract >/dev/null 2>&1; then
    command -v asahi-fwextract
    return 0
  fi
  for candidate in /nix/store/*-asahi-fwextract*/bin/asahi-fwextract; do
    [[ -x $candidate ]] && {
      printf '%s\n' "$candidate"
      return 0
    }
  done
  return 1
}

# ------------------------------------------------------------- probes -------
# Each probe answers "is this step already satisfied?" from live system state,
# so a half-finished run resumes correctly instead of trusting a state file.

probe_detect() { [[ -s $FACTS ]]; }

probe_net() {
  ping -c1 -W3 cache.nixos.org >/dev/null 2>&1 || ping -c1 -W3 github.com >/dev/null 2>&1
}

probe_disk() {
  local root
  root=$(fact_get ROOT_PART 2>/dev/null) || return 1
  [[ -b $root ]]
}

probe_format() {
  local root
  root=$(fact_get ROOT_PART 2>/dev/null) || return 1
  [[ $(blkid -o value -s TYPE "$root" 2>/dev/null) == ext4 ]]
}

probe_mount() {
  findmnt -M "$TARGET" >/dev/null 2>&1 && findmnt -M "$TARGET/boot" >/dev/null 2>&1
}

probe_firmware() { [[ -s $FW_DIR/firmware.cpio ]]; }

probe_config() {
  [[ -f $NIXOS_DIR/configuration.nix ]] || return 1
  [[ -f $NIXOS_DIR/hardware-configuration.nix ]] || return 1
  [[ -d $NIXOS_DIR/apple-silicon-support ]] || return 1
  grep -qF "$CONFIG_MARKER" "$NIXOS_DIR/configuration.nix"
}

probe_install() { [[ -e $TARGET/nix/var/nix/profiles/system ]]; }

probe_stage2() { [[ -x $STAGE2 ]]; }

probe_summary() { return 1; }

# -------------------------------------------------------------- steps -------

step_detect() {
  local disk esp chassis touchbar displays wifi ram_mb ram_gb cores release

  [[ -e /proc/device-tree/chosen/asahi,efi-system-partition ]] \
    || die "no asahi,efi-system-partition in the device tree — this is not the nixos-apple-silicon installer, or the Asahi UEFI environment was never installed"

  esp=$(esp_dev) || die "could not resolve the ESP from the device tree"
  disk=$(detect_disk) || die "could not derive the target disk from the ESP — set DISK=/dev/nvme0n1"
  chassis=$(detect_chassis)
  touchbar=$(detect_touchbar)
  displays=$(detect_displays || true)
  wifi=$(detect_wifi || true)
  ram_mb=$(detect_ram_mb)
  ram_gb=$((ram_mb / 1024))
  cores=$(nproc)
  release=$(detect_release)

  [[ -n $release ]] || die "could not read nixos-version"

  fact_set MODEL "$(dt_string /proc/device-tree/model 2>/dev/null || echo unknown)"
  fact_set COMPATIBLE "$(dt_list /proc/device-tree/compatible 2>/dev/null || echo unknown)"
  fact_set CHASSIS "$chassis"
  fact_set DISK "$disk"
  fact_set ESP "$esp"
  fact_set TOUCHBAR "$touchbar"
  fact_set DISPLAYS "${displays:-unknown}"
  fact_set WIFI "${wifi:-none}"
  fact_set RAM_MB "$ram_mb"
  fact_set CORES "$cores"
  fact_set MAX_JOBS "$(derive_max_jobs "$ram_gb")"
  fact_set SWAP_MB "$(derive_swap_mb "$ram_gb")"
  fact_set BUILD_CORES "$(derive_build_cores "$ram_gb")"
  fact_set RELEASE "$release"
  fact_set TARGET_USER "$TARGET_USER"
  fact_set TARGET_HOST "$TARGET_HOST"
  fact_set TEONIX_REPO "$TEONIX_REPO"
  fact_set TEONIX_DIR "$TEONIX_DIR"
  fact_set CHARGE_LIMIT "$CHARGE_LIMIT"
  [[ -n ${ISO_LAYOUT:-} ]] && fact_set ISO_LAYOUT "$ISO_LAYOUT" || true
  [[ -n ${M1N1_EXTRA:-} ]] && fact_set M1N1_EXTRA "$M1N1_EXTRA" || true
  [[ -n ${PKGS_SYSTEM:-} ]] && fact_set PKGS_SYSTEM "$PKGS_SYSTEM" || true

  ok "detect"
  info "model      $(fact_or MODEL unknown)"
  info "compatible $(fact_or COMPATIBLE unknown)"
  info "chassis    $chassis"
  info "disk       $disk"
  info "esp        $esp"
  info "memory     ${ram_gb} GiB, ${cores} cores -> max-jobs $(fact_or MAX_JOBS 1)"
  info "stage 2    swap $(fact_or SWAP_MB 8192) MiB, build cores $(fact_or BUILD_CORES 2)"
  info "touch bar  $touchbar"
  info "displays   ${displays:-unknown}"
  info "wifi       ${wifi:-none}"
  info "release    $release"
}

step_net() {
  if probe_net; then
    ok "net — already online"
  else
    cat <<'EOF'

No network. Connect Wi-Fi from the installer first:

  iwctl
  [iwd]# station wlan0 scan
  [iwd]# station wlan0 connect YOUR_SSID
  [iwd]# station wlan0 show
  [iwd]# exit

Ethernet over a USB dongle also works. Then re-run this installer.
EOF
    die "no network"
  fi
  systemctl restart systemd-timesyncd 2>/dev/null || true
}

step_disk() {
  local disk root existing=() before=() after=() created=()

  disk=$(fact_get DISK) || die "no disk recorded — run the detect step first"
  [[ -b $disk ]] || die "$disk is not a block device"

  if [[ -n ${ROOT_PART:-} ]]; then
    [[ -b $ROOT_PART ]] || die "ROOT_PART=$ROOT_PART is not a block device"
    fact_set ROOT_PART "$ROOT_PART"
    ok "disk — using ROOT_PART=$ROOT_PART"
    return 0
  fi

  if root=$(labeled_root); then
    fact_set ROOT_PART "$root"
    ok "disk — reusing existing '${ROOT_LABEL}' partition $root"
    return 0
  fi

  mapfile -t existing < <(list_linux_parts "$disk")
  if ((${#existing[@]} == 1)); then
    fact_set ROOT_PART "${existing[0]}"
    ok "disk — reusing existing Linux partition ${existing[0]}"
    return 0
  fi
  if ((${#existing[@]} > 1)); then
    die "several Linux partitions on $disk (${existing[*]}) — choose one with ROOT_PART=/dev/…"
  fi

  say ""
  sgdisk -p "$disk" || true
  cat <<EOF

About to create ONE new partition filling the free space on $disk.
macOS, the iBoot container, the ESP and the Recovery container are untouched.
EOF
  confirm "Create the NixOS root partition on $disk?"

  mapfile -t before < <(list_parts "$disk")
  sgdisk "$disk" -n "0:0:0" -t "0:8300" -c "0:${ROOT_LABEL}" -s
  reread_pt "$disk"
  mapfile -t after < <(list_parts "$disk")

  mapfile -t created < <(
    comm -13 \
      <(printf '%s\n' "${before[@]+${before[@]}}" | LC_ALL=C sort) \
      <(printf '%s\n' "${after[@]+${after[@]}}" | LC_ALL=C sort)
  )

  for root in "${created[@]+${created[@]}}"; do
    [[ -b $root ]] || continue
    fact_set ROOT_PART "$root"
    ok "disk — created $root"
    return 0
  done

  die "sgdisk reported success but no new partition appeared — inspect 'sgdisk -p $disk' and re-run with ROOT_PART=/dev/…"
}

step_format() {
  local root fstype
  root=$(fact_get ROOT_PART) || die "no root partition recorded — run the disk step first"
  fstype=$(blkid -o value -s TYPE "$root" 2>/dev/null || true)

  if [[ $fstype == ext4 && ${FORMAT:-0} != 1 ]]; then
    skip "format — $root is already ext4 (FORMAT=1 to erase it)"
    return 0
  fi
  if [[ -n $fstype && ${FORMAT:-0} != 1 ]]; then
    die "$root already holds a '$fstype' filesystem — set FORMAT=1 to erase it"
  fi

  confirm "Format $root as ext4? This erases that partition only."
  mkfs.ext4 -F -L "$ROOT_LABEL" "$root"
  ok "format — $root is ext4, label ${ROOT_LABEL}"
}

step_mount() {
  local root esp
  root=$(fact_get ROOT_PART) || die "no root partition recorded — run the disk step first"

  findmnt -M "$TARGET" >/dev/null 2>&1 || mount "$root" "$TARGET"

  mkdir -p "$TARGET/boot"
  if ! findmnt -M "$TARGET/boot" >/dev/null 2>&1; then
    esp=$(esp_dev) || die "could not resolve the ESP"
    mount "$esp" "$TARGET/boot"
  fi

  ok "mount — $(findmnt -no SOURCE "$TARGET") on $TARGET, $(findmnt -no SOURCE "$TARGET/boot") on $TARGET/boot"
}

# Wi-Fi, Bluetooth, camera and the ambient light sensor need Apple's
# non-redistributable firmware. The ESP carries it as a raw asahi/ tree; the
# cpio archive the module wants is produced by asahi-fwextract, exactly like
# the ISO does in its own boot.postBootCommands.
step_firmware() {
  local cpio="$FW_DIR/firmware.cpio" fwextract

  if [[ -s $cpio && ${FORCE:-0} != 1 ]]; then
    skip "firmware — $cpio already present"
    return 0
  fi

  mkdir -p "$FW_DIR"

  if [[ -s $TARGET/boot/vendorfw/firmware.cpio ]]; then
    cp -f "$TARGET/boot/vendorfw/firmware.cpio" "$cpio"
    ok "firmware — copied from the ESP's vendorfw/"
    return 0
  fi

  if [[ ! -d $TARGET/boot/asahi ]]; then
    warn "no vendorfw/ or asahi/ on the ESP — Wi-Fi, Bluetooth and the camera will not work"
    warn "boot macOS, run 'curl https://alx.sh | sh', pick 'Rebuild vendor firmware package', then re-run this step"
    rmdir "$FW_DIR" 2>/dev/null || true
    return 0
  fi

  fwextract=$(find_fwextract) \
    || die "asahi-fwextract is not in this installer's store — copy vendorfw/firmware.cpio to $cpio by hand and re-run"

  "$fwextract" "$TARGET/boot/asahi" "$FW_DIR"
  [[ -s $cpio ]] || die "asahi-fwextract did not produce $cpio"
  ok "firmware — extracted from the ESP's asahi/ with $(basename "$fwextract")"
}

step_config() {
  local iso_module=/etc/nixos/apple-silicon-support

  [[ -d $iso_module ]] \
    || die "$iso_module is missing — this ISO is not from nixos-apple-silicon, so its Asahi kernel cannot be reused"

  mkdir -p "$NIXOS_DIR"
  nixos-generate-config --root "$TARGET"

  # The ISO plants its own apple-silicon-support in /etc/nixos. Copying it
  # (rather than pinning a flake input) is what keeps the kernel identical to
  # the one already built into this installer.
  rm -rf "$NIXOS_DIR/apple-silicon-support"
  cp -r "$iso_module" "$NIXOS_DIR/apple-silicon-support"
  chmod -R u+w "$NIXOS_DIR/apple-silicon-support"

  write_configuration >"$NIXOS_DIR/configuration.nix"
  cp -f "$FACTS" "$NIXOS_DIR/applenix-facts.txt"

  ok "config — wrote $NIXOS_DIR/configuration.nix against the ISO's nixpkgs and apple-silicon-support"
}

step_install() {
  if probe_install && [[ ${FORCE:-0} != 1 ]]; then
    skip "install — a system profile already exists under $TARGET/nix (FORCE=1 to install again)"
    return 0
  fi

  say ""
  info "running nixos-install; the kernel is copied from the installer, so this"
  info "should take minutes rather than hours"
  say ""

  nixos-install --root "$TARGET" --no-root-password

  ok "install — stage 1 system installed"
}

step_stage2() {
  mkdir -p "$(dirname "$STAGE2")"
  write_stage2 >"$STAGE2"
  chmod +x "$STAGE2"
  ok "stage2 — installed ${STAGE2#"${TARGET%/}"} on the new system"
}

step_summary() {
  local user host displays
  user=$(fact_or TARGET_USER "$TARGET_USER")
  host=$(fact_or TARGET_HOST "$TARGET_HOST")
  displays=$(fact_or DISPLAYS unknown)

  cat <<EOF

──────────────────────────────────────────────────────────────
 Stage 1 done: ${host} is installed and bootable.
──────────────────────────────────────────────────────────────

  reboot          (then unplug the USB stick)

Log in as ${user} / ${user} on the text console, then:

  passwd
  /etc/applenix/stage2.sh

Stage 2 clones teonix, copies this Mac's hardware config and Asahi
firmware into the flake, and switches to the #applenix Hyprland rice.
It does not need --impure.

Detected displays: ${displays}
If Hyprland or Quickshell come up on the wrong output, adjust
home/hosts/applenix/dotfiles/config/hypr/hyprland.conf and
home/hosts/applenix/dotfiles/config/quickshell/Globals.qml.
EOF
}

# ------------------------------------------- generated stage 1 config -------

write_configuration() {
  local user host release ram_gb max_jobs cores chassis touchbar
  local fw_fragment="" touchbar_fragment="" battery_fragment=""
  local m1n1_fragment="" modprobe_fragment="" pkgs_system_fragment=""

  user=$(fact_or TARGET_USER "$TARGET_USER")
  host=$(fact_or TARGET_HOST "$TARGET_HOST")
  release=$(fact_get RELEASE)
  ram_gb=$(($(fact_or RAM_MB 4096) / 1024))
  max_jobs=$(fact_or MAX_JOBS 1)
  cores=$(fact_or CORES 4)
  chassis=$(fact_or CHASSIS desktop)
  touchbar=$(fact_or TOUCHBAR no)

  if [[ -s $FW_DIR/firmware.cpio ]]; then
    fw_fragment="  hardware.asahi.extractPeripheralFirmware = true;
  hardware.asahi.peripheralFirmwareDirectory = ./firmware;"
  else
    fw_fragment="  # No firmware.cpio was found on the ESP; Wi-Fi and the camera stay dark
  # until you rebuild the vendor firmware package from macOS.
  hardware.asahi.extractPeripheralFirmware = false;"
  fi

  if [[ $touchbar == yes ]]; then
    touchbar_fragment="
  hardware.apple.touchBar.enable = true;"
  fi

  if [[ $chassis == laptop ]]; then
    battery_fragment="
  services.udev.extraRules = ''
    SUBSYSTEM==\"power_supply\", KERNEL==\"macsmc-battery\", ATTR{charge_control_end_threshold}=\"$(fact_or CHARGE_LIMIT "$CHARGE_LIMIT")\"
  '';"
  fi

  if [[ -n $(fact_get M1N1_EXTRA 2>/dev/null || true) ]]; then
    m1n1_fragment="
  boot.m1n1ExtraOptions = \"$(fact_get M1N1_EXTRA)\";"
  fi

  if [[ -n $(fact_get ISO_LAYOUT 2>/dev/null || true) ]]; then
    modprobe_fragment="
  boot.extraModprobeConfig = ''
    options hid_apple iso_layout=$(fact_get ISO_LAYOUT)
  '';"
  fi

  if [[ -n $(fact_get PKGS_SYSTEM 2>/dev/null || true) ]]; then
    pkgs_system_fragment="
  # Matches the build platform of a cross-built installer ISO so its
  # prebuilt Asahi kernel is reused instead of rebuilt.
  hardware.asahi.pkgsSystem = \"$(fact_get PKGS_SYSTEM)\";"
  fi

  cat <<EOF
${CONFIG_MARKER}${VERSION} on $(date -u '+%Y-%m-%d %H:%M UTC')
#
# Stage 1: minimal console system for ${host}.
#
# This is deliberately a plain configuration.nix, not a flake. It builds
# against the ISO's nixpkgs and the apple-silicon-support copied out of the
# ISO, so nixos-install reuses the installer's Asahi kernel instead of
# rebuilding it. Do not "upgrade" this to the teonix flake — that is what
# stage 2 (/etc/applenix/stage2.sh) is for.
#
# Detected: $(fact_or MODEL unknown) / $(fact_or COMPATIBLE unknown)
# ${ram_gb} GiB RAM, ${cores} cores, ${chassis}
{ config, lib, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./apple-silicon-support
  ];

  hardware.asahi.enable = true;
  hardware.asahi.setupAsahiSound = true;
${fw_fragment}${pkgs_system_fragment}

  # Apple firmware and U-Boot own the boot picker, so never write EFI vars.
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.configurationLimit = 10;
  boot.loader.efi.canTouchEfiVariables = false;
${m1n1_fragment}${modprobe_fragment}

  networking.hostName = "${host}";
  networking.networkmanager.enable = true;
  # wpa_supplicant cannot do WPA3 on the Broadcom parts Apple ships.
  networking.networkmanager.wifi.backend = "iwd";
${touchbar_fragment}${battery_fragment}

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    max-jobs = ${max_jobs};
    cores = ${cores};
    trusted-users = [ "root" "@wheel" ];
    substituters = [
      "https://cache.nixos.org"
      "https://nix-community.cachix.org"
    ];
    trusted-public-keys = [
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };

  nixpkgs.config.allowUnfree = true;

  users.mutableUsers = true;
  users.users.${user} = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" "video" "input" "audio" ];
    initialPassword = "${user}";
  };
  users.users.root.initialPassword = "${user}";

  environment.systemPackages = with pkgs; [
    git
    vim
    tmux
    curl
    htop
  ];

  zramSwap.enable = true;

  services.getty.helpLine = ''

    ${host} stage 1. Login: ${user} / ${user} — change it with passwd.
    Then run stage 2 to switch to the teonix rice:
      /etc/applenix/stage2.sh
  '';

  system.stateVersion = "${release}";
}
EOF
}

# ------------------------------------------------ generated stage 2 ---------

write_stage2() {
  cat <<EOF
#!/usr/bin/env bash
#
# applenix stage 2 — switch this Mac from the stage 1 console system to the
# teonix #applenix Hyprland rice. Generated by ${SELF} v${VERSION}.
#
# Run it as ${TARGET_USER} (not root), from a booted applenix:
#   /etc/applenix/stage2.sh
#
# Safe to re-run: every step checks its own result first.
#
set -euo pipefail

REPO="\${TEONIX_REPO:-$(fact_or TEONIX_REPO "$TEONIX_REPO")}"
DIR="\${TEONIX_DIR:-$(fact_or TEONIX_DIR "$TEONIX_DIR")}"
FACTS=/etc/nixos/applenix-facts.txt
HOST_DIR="\$DIR/hosts/applenix"
SWAPFILE=/swapfile

say() { printf '%s\\n' "\$*"; }
ok() { printf '[ ok ] %s\\n' "\$*"; }
skip() { printf '[skip] %s\\n' "\$*"; }
warn() { printf '[warn] %s\\n' "\$*" >&2; }
die() { printf 'error: %s\\n' "\$*" >&2; exit 1; }

fact() {
  local value
  [[ -f \$FACTS ]] || return 1
  value=\$(sed -n "s/^\$1=//p" "\$FACTS" | tail -n1)
  [[ -n \$value ]] || return 1
  printf '%s\\n' "\$value"
}

[[ \$(id -u) -ne 0 ]] || die "run this as your normal user, not root; it calls sudo itself"
command -v git >/dev/null || die "git is missing — 'nix-shell -p git' or fix stage 1 first"

ram_gb=\$(awk '/^MemTotal:/ { printf "%d\\n", \$2 / 1048576 }' /proc/meminfo)

# --- swap ------------------------------------------------------------------
# The teonix flake pins its own nixpkgs and apple-silicon, so this switch does
# rebuild the Asahi kernel. On disk that is fine; without swap an 8 GB Mac OOMs.
#
# The floor is recomputed from RAM rather than trusted from the facts file, so
# a machine written by an older installer still gets enough swap here.
if ((ram_gb <= 8)); then
  swap_floor=16384
elif ((ram_gb <= 16)); then
  swap_floor=12288
else
  swap_floor=8192
fi

if [[ -n \${SWAP_MB:-} ]]; then
  swap_mb=\$SWAP_MB
else
  swap_mb=\$(fact SWAP_MB 2>/dev/null || echo 0)
  ((swap_mb >= swap_floor)) || swap_mb=\$swap_floor
fi

file_mb=0
[[ -f \$SWAPFILE ]] && file_mb=\$(( \$(stat -c %s "\$SWAPFILE") / 1048576 ))

if ((file_mb >= swap_mb)); then
  skip "swap — \$SWAPFILE is already \${file_mb} MiB"
else
  # A too-small file from an earlier run is worse than none: it looks like swap
  # exists while the build still dies. Replace it.
  if ((file_mb > 0)); then
    warn "\$SWAPFILE is only \${file_mb} MiB; growing it to \${swap_mb} MiB"
    sudo swapoff "\$SWAPFILE" 2>/dev/null || true
    sudo rm -f "\$SWAPFILE"
  fi

  free_mb=\$(df --output=avail -BM / | awk 'NR == 2 { gsub(/M/, ""); print }')
  if ((free_mb < swap_mb + 20480)); then
    swap_mb=\$(( free_mb > 25600 ? free_mb - 20480 : 0 ))
    ((swap_mb > 0)) || die "not enough free space on / for a swapfile (\${free_mb} MiB free)"
    warn "trimming the swapfile to \${swap_mb} MiB to leave room for /nix/store"
  fi

  say "creating a \${swap_mb} MiB swapfile at \$SWAPFILE for the kernel build"
  sudo fallocate -l "\${swap_mb}M" "\$SWAPFILE" 2>/dev/null \\
    || sudo dd if=/dev/zero of="\$SWAPFILE" bs=1M count="\$swap_mb" status=progress
  sudo chmod 600 "\$SWAPFILE"
  sudo mkswap "\$SWAPFILE"
  sudo swapon "\$SWAPFILE" || die "swapon \$SWAPFILE failed; the build would OOM without it"
  ok "swap — \${swap_mb} MiB at \$SWAPFILE"
fi

# /proc/swaps separates its columns with tabs, so compare fields, not a prefix.
swap_active() {
  awk -v want="\$1" 'NR > 1 && \$1 == want { hit = 1 } END { exit !hit }' /proc/swaps
}
swap_active "\$SWAPFILE" || sudo swapon "\$SWAPFILE" \\
  || die "swapon \$SWAPFILE failed; the build would OOM without it"

# zram sits at a higher swap priority than a file, so without this a big build
# compresses its pages into RAM — the one place we are short — instead of
# spilling to disk. #applenix does not enable zram, so this only affects the
# stage 1 system we are building from.
if grep -q '^/dev/zram' /proc/swaps; then
  sudo swapoff /dev/zram0 2>/dev/null \\
    && ok "zram — off for the build, so pages reach the real swapfile" \\
    || warn "could not disable zram; the build may still OOM"
fi

# --- repo ------------------------------------------------------------------
# An older bootstrap.sh used to overwrite tracked files in this checkout in
# place. A plain "git pull --ff-only" then refuses, and building anyway meant
# compiling for an hour only to fail on a stale asahi.nix. So: stash anything
# the user changed, then take upstream's tree verbatim.
if [[ -d \$DIR/.git ]]; then
  say "updating \$DIR"
  git -C "\$DIR" fetch --prune origin || warn "git fetch failed; working offline"

  branch=\$(git -C "\$DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo main)
  upstream=\$(git -C "\$DIR" rev-parse --abbrev-ref --symbolic-full-name '@{upstream}' 2>/dev/null \\
    || echo "origin/\$branch")

  # hardware-configuration.nix and detected.nix are ours; we rewrite them below.
  dirty=\$(git -C "\$DIR" status --porcelain --untracked-files=no \\
    | awk '{ print \$NF }' \\
    | grep -v -e '^hosts/applenix/hardware-configuration.nix\$' \\
      -e '^hosts/applenix/detected.nix\$' || true)

  if [[ -n \$dirty ]]; then
    warn "local edits to tracked files:"
    printf '         %s\\n' \$dirty >&2
    git -C "\$DIR" stash push -m "applenix-stage2 \$(date -Iseconds)" \\
      && warn "stashed them; recover with: git -C \$DIR stash list" \\
      || warn "stash failed; continuing with a hard reset"
  fi

  git -C "\$DIR" reset --hard "\$upstream" \\
    || die "could not reset \$DIR to \$upstream — fix the checkout by hand, or delete \$DIR and re-run"
  ok "repo — \$DIR at \$(git -C "\$DIR" rev-parse --short HEAD) (\$upstream)"
else
  say "cloning \$REPO into \$DIR"
  mkdir -p "\$(dirname "\$DIR")"
  git clone "\$REPO" "\$DIR"
  ok "repo — cloned to \$DIR"
fi

[[ -f \$DIR/flake.nix ]] || die "\$DIR/flake.nix is missing — wrong repo?"
mkdir -p "\$HOST_DIR"

# Cheap guard against the class of failure that costs a whole kernel build:
# linux-asahi dropped the ignoreConfigErrors argument in release-2026-07-30.
#
# Only .nix files, and only outside comments: the word also appears in this
# installer, in INSTALL.md, and in a comment in asahi.nix explaining why the
# argument is gone. A recursive grep for the bare word matches all three and
# fails a checkout that is perfectly correct.
offenders=""
for nix_file in "\$HOST_DIR"/*.nix; do
  [[ -f \$nix_file ]] || continue
  if sed 's/#.*//' "\$nix_file" | grep -q 'ignoreConfigErrors'; then
    offenders+="\$(basename "\$nix_file") "
  fi
done
if [[ -n \$offenders ]]; then
  die "\$HOST_DIR still passes ignoreConfigErrors to linux-asahi: \$offenders
       (leftover from the retired bootstrap.sh, which overwrote tracked files in place)
       Clean the checkout, then re-run:
         git -C \$DIR fetch origin && git -C \$DIR reset --hard origin/main"
fi

# --- this Mac's real hardware config ---------------------------------------
if [[ -f /etc/nixos/hardware-configuration.nix ]]; then
  sudo cp /etc/nixos/hardware-configuration.nix "\$HOST_DIR/hardware-configuration.nix"
  sudo chown "\$(id -u):\$(id -g)" "\$HOST_DIR/hardware-configuration.nix"
  # Firmware handling belongs to asahi.nix, not to the generated hardware file.
  sed -i '/extractPeripheralFirmware/d' "\$HOST_DIR/hardware-configuration.nix"
  ok "hardware — real UUIDs from this Mac"
else
  warn "no /etc/nixos/hardware-configuration.nix; keeping the repo placeholder"
fi

# --- Asahi peripheral firmware inside the flake ----------------------------
# Keeping firmware.cpio in the flake directory is what lets #applenix
# evaluate purely, with no --impure.
mkdir -p "\$HOST_DIR/firmware"
if [[ -s \$HOST_DIR/firmware/firmware.cpio ]]; then
  skip "firmware — already in the flake"
elif [[ -s /etc/nixos/firmware/firmware.cpio ]]; then
  cp -f /etc/nixos/firmware/firmware.cpio "\$HOST_DIR/firmware/firmware.cpio"
  ok "firmware — copied from /etc/nixos/firmware"
elif [[ -s /boot/vendorfw/firmware.cpio ]]; then
  sudo cp -f /boot/vendorfw/firmware.cpio "\$HOST_DIR/firmware/firmware.cpio"
  sudo chown "\$(id -u):\$(id -g)" "\$HOST_DIR/firmware/firmware.cpio"
  ok "firmware — copied from the ESP"
else
  rmdir "\$HOST_DIR/firmware" 2>/dev/null || true
  warn "no firmware.cpio found; Wi-Fi and the camera will not work"
fi

# --- machine-specific overrides -------------------------------------------
touchbar=\$(fact TOUCHBAR 2>/dev/null || echo no)
chassis=\$(fact CHASSIS 2>/dev/null || echo desktop)
displays=\$(fact DISPLAYS 2>/dev/null || echo unknown)
m1n1=\$(fact M1N1_EXTRA 2>/dev/null || true)
iso_layout=\$(fact ISO_LAYOUT 2>/dev/null || true)

{
  echo "# Generated by /etc/applenix/stage2.sh from \$FACTS."
  echo "# Machine-specific bits detected on this Mac. Safe to commit."
  echo "#"
  echo "# Model:    \$(fact MODEL 2>/dev/null || echo unknown)"
  echo "# Chassis:  \$chassis"
  echo "# Displays: \$displays"
  echo "#           (set the Hyprland monitor and Quickshell shellMonitor to match)"
  echo "{ lib, pkgs, ... }:"
  echo ""
  echo "{"
  if [[ \$touchbar == yes ]]; then
    echo "  hardware.apple.touchBar.enable = true;"
  fi
  if [[ -n \$m1n1 ]]; then
    echo "  boot.m1n1ExtraOptions = \\"\$m1n1\\";"
  fi
  if [[ -n \$iso_layout ]]; then
    echo "  boot.extraModprobeConfig = ''"
    echo "    options hid_apple iso_layout=\$iso_layout"
    echo "  '';"
  fi
  echo "  swapDevices = [ { device = \\"\$SWAPFILE\\"; size = \$swap_mb; } ];"
  echo "}"
} >"\$HOST_DIR/detected.nix"
ok "detected — wrote \$HOST_DIR/detected.nix"

# --- kernel sanity ---------------------------------------------------------
# linux-asahi is in no binary cache, so if its path is not already in the store
# the switch silently turns into a 2h+ compile that OOMs small Macs. asahi.nix
# pins it to apple-silicon's own nixpkgs precisely so it matches the kernel the
# installer copied here; check that held before committing to a long run.
say "checking the Asahi kernel is prebuilt (this is the 2h trap)"
kernel=\$(nix eval --raw "path:\$DIR#nixosConfigurations.applenix.config.boot.kernelPackages.kernel" 2>/dev/null || true)

if [[ -z \$kernel ]]; then
  warn "could not evaluate the kernel path; continuing without the check"
elif nix path-info "\$kernel" >/dev/null 2>&1; then
  ok "kernel — \${kernel##*/} already in the store, nothing to compile"
else
  warn "the Asahi kernel is NOT in the store and no cache has it:"
  warn "  \$kernel"
  warn "Switching now would compile it: 2h+, and it OOMs an 8 GB Mac."
  warn "This means the flake's apple-silicon input no longer matches the ISO"
  warn "this Mac was installed from. Fix the pin rather than build the kernel."
  warn "The kernel this Mac is actually running is:"
  warn "  \$(readlink -f /run/current-system/kernel 2>/dev/null || echo unknown)"
  if [[ \${KERNEL_BUILD_OK:-0} != 1 ]]; then
    die "refusing to start a kernel build; re-run with KERNEL_BUILD_OK=1 to do it anyway"
  fi
  warn "KERNEL_BUILD_OK=1 set — building the kernel as requested"
fi

# --- switch ----------------------------------------------------------------
# max-jobs 1 keeps two heavy derivations from running at once; cores bounds the
# parallelism inside one, which is what actually sets peak memory. rustc in the
# Asahi kernel is the expensive part, so a small Mac must not use every core.
if [[ -n \${BUILD_CORES:-} ]]; then
  cores=\$BUILD_CORES
elif cores=\$(fact BUILD_CORES 2>/dev/null); then
  :
elif ((ram_gb <= 8)); then
  cores=2
elif ((ram_gb <= 16)); then
  cores=4
else
  cores=0 # 0 = all
fi
swap_active_mb=\$(awk 'NR > 1 { total += \$3 } END { printf "%d\\n", total / 1024 }' /proc/swaps)

say ""
say "switching to #applenix; the Asahi kernel builds here, so expect a long run"
say "  RAM \${ram_gb} GiB, swap \${swap_active_mb} MiB, max-jobs 1, cores \$cores"
say "  if this still gets killed, re-run with: BUILD_CORES=1 \$0"
say "  (use tmux if you are over ssh)"
say ""
cd "\$DIR"
sudo nixos-rebuild switch --flake "path:.#applenix" \\
  --option max-jobs 1 \\
  --option cores "\$cores"

say ""
ok "stage 2 complete"
say "reboot, then pick Hyprland at the display manager"
EOF
}

# ---------------------------------------------------------- dispatcher ------

run_step() {
  local step=$1 fn="step_${1}" probe="probe_${1}"

  [[ $(type -t "$fn") == function ]] || die "unknown step: $step"

  if [[ ${FORCE:-0} != 1 ]] && "$probe" 2>/dev/null; then
    skip "$step"
    return 0
  fi

  CURRENT_STEP=$step
  runmsg "$step"
  "$fn"
  CURRENT_STEP=""
}

cmd_status() {
  local step state detail

  say "${SELF} v${VERSION}"
  say "  facts   $FACTS"
  say "  target  $TARGET"
  say "  disk    $(fact_or DISK '(not detected yet)')"
  say "  root    $(fact_or ROOT_PART '(not chosen yet)')"
  say ""
  printf '%-10s %-8s %s\n' STEP STATE DETAIL

  for step in "${STEPS[@]}"; do
    detail=""
    case $step in
      detect) detail="$(fact_or MODEL '-')" ;;
      net) probe_net && detail="online" || detail="offline" ;;
      disk) detail="$(fact_or ROOT_PART '-')" ;;
      format)
        detail=$(blkid -o value -s TYPE "$(fact_or ROOT_PART /dev/null)" 2>/dev/null || echo "-")
        ;;
      mount)
        findmnt -M "$TARGET" >/dev/null 2>&1 \
          && detail="$(findmnt -no SOURCE "$TARGET") + $(findmnt -no SOURCE "$TARGET/boot" 2>/dev/null || echo 'no esp')" \
          || detail="not mounted"
        ;;
      firmware) [[ -s $FW_DIR/firmware.cpio ]] && detail="present" || detail="missing" ;;
      config) [[ -f $NIXOS_DIR/configuration.nix ]] && detail="$NIXOS_DIR" || detail="-" ;;
      install) probe_install && detail="system profile exists" || detail="-" ;;
      stage2) [[ -x $STAGE2 ]] && detail="${STAGE2#"${TARGET%/}"}" || detail="-" ;;
      summary) detail="-" ;;
    esac

    if "probe_${step}" 2>/dev/null; then
      state="done"
    else
      state="pending"
    fi
    printf '%-10s %-8s %s\n' "$step" "$state" "$detail"
  done
}

usage() {
  cat <<EOF
${SELF} v${VERSION} — stage 1 installer for any Apple Silicon Mac

Usage, as root from the nixos-apple-silicon USB installer:

  ${CURL_CMD}

  … all              run every pending step (default)
  … status           show the live checklist
  … list             print step names
  … run STEP [STEP]  run only these steps
  … help             this text

Steps: ${STEPS[*]}

Environment:
  YES=1            skip confirmation prompts
  FORCE=1          redo steps even when they look finished
  FORMAT=1         allow mkfs over an existing filesystem
  DISK=/dev/…      target disk (default: the disk holding the Asahi ESP)
  ROOT_PART=/dev/… use this partition instead of creating one
  TARGET_USER=…    first user (default teodor)
  TARGET_HOST=…    hostname (default applenix)
  TOUCHBAR=yes|no  override Touch Bar detection
  ISO_LAYOUT=0|1   hid_apple iso_layout, if \` and < are swapped
  M1N1_EXTRA=…     boot.m1n1ExtraOptions, for Mac mini display quirks
  SWAP_SIZE=MiB    swap the stage 2 helper creates (default from RAM)
  BUILD_CORES=N    cores per derivation in stage 2; lower it if the build OOMs
  KERNEL_BUILD_OK=1 let stage 2 compile the Asahi kernel instead of refusing
  PKGS_SYSTEM=…    set if the ISO was cross-built and the kernel rebuilds
  CHARGE_LIMIT=…   battery charge ceiling on laptops (default 80)
  TEONIX_REPO=…    repo stage 2 clones
  TEONIX_DIR=…     where stage 2 clones it

To resume after any failure, just run the same command again.
EOF
}

main() {
  local step

  case ${1:-all} in
    help | -h | --help)
      usage
      ;;
    list)
      printf '%s\n' "${STEPS[@]}"
      ;;
    status)
      cmd_status
      ;;
    run)
      need_root
      shift
      (($#)) || die "run needs at least one step name"
      for step in "$@"; do
        run_step "$step"
      done
      ;;
    all)
      need_root
      say "${SELF} v${VERSION}"
      say ""
      for step in "${STEPS[@]}"; do
        run_step "$step"
      done
      ;;
    *)
      # Bare step names are accepted too: … mount firmware
      need_root
      for step in "$@"; do
        run_step "$step"
      done
      ;;
  esac
}

main "$@"
